### ISSUE TITLE
Running failed

### ISSUE THREAD

**Issue by define-private-public** [nlowe/dotnet-opentk-tutorial#1]
Thanks for putting this up.  I've been trying to find some .NET Core OpenGL examples (that run on Linux) and it's been a tad hard to find something that at least builds (this did).  But when doing the `dotnet run`.  I was treated with this:

```
Unhandled Exception: System.MissingMethodException: Method not found: '!0 System.ReadOnlySpan`1.get_Item(Int32)'.
   at SixLabors.ImageSharp.Formats.Bmp.BmpImageFormatDetector.IsSupportedFileFormat(ReadOnlySpan`1 header)
   at SixLabors.ImageSharp.Formats.Bmp.BmpImageFormatDetector.DetectFormat(ReadOnlySpan`1 header)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at SixLabors.ImageSharp.Image.InternalDetectFormat(Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Stream stream)
   at dotnet_opentk_tutorial.Rendering.TexturedRenderObject.LoadTexture(String texturePath, Int32& w, Int32& h) in /home/ben/Projects/third_party/dotnet-opentk-tutorial/Rendering/TexturedRenderObject.cs:line 96
   at dotnet_opentk_tutorial.Rendering.TexturedRenderObject.InitTextures(String texturePath) in /home/ben/Projects/third_party/dotnet-opentk-tutorial/Rendering/TexturedRenderObject.cs:line 56
   at dotnet_opentk_tutorial.Rendering.TexturedRenderObject..ctor(IReadOnlyCollection`1 vertices, ShaderProgram shaderProgram, String texturePath) in /home/ben/Projects/third_party/dotnet-opentk-tutorial/Rendering/TexturedRenderObject.cs:line 51
   at dotnet_opentk_tutorial.Actors.ActorFactory..ctor(ShaderProgram coloredSolidShader, ShaderProgram texturedSolidShader) in /home/ben/Projects/third_party/dotnet-opentk-tutorial/Actors/ActorFactory.cs:line 25
   at dotnet_opentk_tutorial.Components.MainWindow.OnLoad(EventArgs e) in /home/ben/Projects/third_party/dotnet-opentk-tutorial/Components/MainWindow.cs:line 71
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at dotnet_opentk_tutorial.Program.Main(String[] args) in /home/ben/Projects/third_party/dotnet-opentk-tutorial/Program.cs:line 11
```

Any idea on how to fix this?

**Comment by nlowe** [comment]
What version of the .NET SDK and Runtimes do you have installed? This sounds like a mixup with targets and the runtime.

**Comment by define-private-public** [comment]
I've got the 2.1, 2.2, and the 3.1 SDKs installed

**Comment by nlowe** [comment]
I think some of the span changes introduced in 3.0+ are conflicting with the old version of ImageSharp I was pulling in. Does this diff work for you?

```diff
diff --git a/Rendering/TexturedRenderObject.cs b/Rendering/TexturedRenderObject.cs
index 4934d56..06310b9 100644
--- a/Rendering/TexturedRenderObject.cs
+++ b/Rendering/TexturedRenderObject.cs
@@ -4,6 +4,8 @@ using System.IO;
 using System.Linq;
 using OpenTK.Graphics.OpenGL4;
 using SixLabors.ImageSharp;
+using SixLabors.ImageSharp.Advanced;^M
+using SixLabors.ImageSharp.PixelFormats;^M

 namespace dotnet_opentk_tutorial.Rendering
 {
@@ -100,9 +102,12 @@ namespace dotnet_opentk_tutorial.Rendering

                 var result = new float[4 * w * h];
                 var i = 0;
-                foreach (var pixel in image.SavePixelData())
+                foreach (var pixel in image.GetPixelSpan())^M
                 {
-                    result[i++] = pixel / 255f;
+                       result[i++] = pixel.R / 255f;^M
+                       result[i++] = pixel.G / 255f;^M
+                       result[i++] = pixel.B / 255f;^M
+                       result[i++] = pixel.A / 255f;^M
                 }

                 return result;
diff --git a/dotnet-opentk-tutorial.csproj b/dotnet-opentk-tutorial.csproj
index be67ca2..6ab9ffd 100644
--- a/dotnet-opentk-tutorial.csproj
+++ b/dotnet-opentk-tutorial.csproj
@@ -5,6 +5,6 @@
   </PropertyGroup>
   <ItemGroup>
     <PackageReference Include="OpenTK.NETCore" Version="1.1.2749.6433" />
-    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0002" />
+    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0007" />^M
   </ItemGroup>
 </Project>
\ No newline at end of file
```

It seems to run on windows with these changes:

![image](https://user-images.githubusercontent.com/794251/74298437-c69d3700-4d17-11ea-9ac1-b8211132e8cd.png)

**Comment by define-private-public** [comment]
Works like a charm!  Thanks!
